name: adocao_animais
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.5
  brasil_fields: ^1.14.0
  google_fonts: ^4.0.1
  image_picker: ^0.8.4+2
  firebase_storage: ^11.5.3
  firebase_core: ^2.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  intl: ^0.18.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/dog_and_cat.png
    - lib/assets/patas.png
    - lib/assets/coracao_patas.png
    - lib/assets/icon_cachorro.png
    - lib/assets/icon_gato.png
    - lib/assets/icon_coelho.png
    - lib/assets/icon_papagaio.png
    - lib/assets/pet_add.png
    - lib/assets/gato_1.png
    - lib/assets/icon_adocao.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
